import {THREE,scene,moving,ball,group,animations,waterMeshes,windows,range,rand} from './core.js';
import {chimneys} from './village.js';
export const environment={weather:'clear',hour:15,wind:.45,motion:true};
export const sun=new THREE.DirectionalLight(0xffeed0,2.6),ambient=new THREE.HemisphereLight(0xe7efe4,0x919676,2.25);sun.position.set(-17,30,13);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:1,far:85});sun.shadow.bias=-.0007;sun.shadow.normalBias=.04;sun.shadow.radius=3;scene.add(sun,ambient);scene.fog=new THREE.FogExp2(0xdde5d8,.005);
const smoke=[];let drops,rain,snow,clouds=[];
export function buildAtmosphere(){for(const p of chimneys)for(let i=0;i<7;i++){const material=new THREE.MeshBasicMaterial({color:0xe4e5db,transparent:true,opacity:.15,depthWrite:false});const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.13,1),material);moving.add(m);smoke.push({mesh:m,origin:p,phase:i/7});}
for(const [x,y,z,s]of[[-11,11,-15,1.3],[7,12,-15,1.7],[-15,9,0,.8],[15,11,-5,1]]){const g=group(x,y,z,moving);for(let i=0;i<5;i++){const b=ball(s*range(.35,.65),0xf1f0df,(i-2)*s*.6,Math.sin(i)*s*.18,0,g,1);b.scale.set(1.55,.56,.75);b.castShadow=false;b.material=new THREE.MeshBasicMaterial({color:0xf5f4e8,transparent:true,opacity:.52,depthWrite:false});}clouds.push({g,x,z,phase:rand()*6});}
const count=650,positions=new Float32Array(count*6);for(let i=0;i<count;i++){let x=range(-16,16),y=range(0,20),z=range(-16,16);positions.set([x,y,z,x-.07,y+.40,z-.02],i*6);}const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.BufferAttribute(positions,3));rain=new THREE.LineSegments(geom,new THREE.LineBasicMaterial({color:0xaec8cf,transparent:true,opacity:.47}));rain.visible=false;scene.add(rain);
const sg=new THREE.BufferGeometry(),sp=new Float32Array(count*3);for(let i=0;i<sp.length;i++)sp[i]=i%3===1?range(0,18):range(-16,16);sg.setAttribute('position',new THREE.BufferAttribute(sp,3));const c=document.createElement('canvas');c.width=c.height=32;const ctx=c.getContext('2d'),r=ctx.createRadialGradient(16,16,0,16,16,16);r.addColorStop(0,'#ffffff');r.addColorStop(.5,'#ffffff');r.addColorStop(1,'#ffffff00');ctx.fillStyle=r;ctx.fillRect(0,0,32,32);snow=new THREE.Points(sg,new THREE.PointsMaterial({color:0xffffff,size:.14,transparent:true,opacity:.8,map:new THREE.CanvasTexture(c),depthWrite:false}));snow.visible=false;scene.add(snow);
}
const clearBG=new THREE.Color(0xe2e9df),nightBG=new THREE.Color(0x344d59),wetBG=new THREE.Color(0xa5b6b3),fogBG=new THREE.Color(0xcbd4c6),snowBG=new THREE.Color(0xd8e4e3);
export function updateAtmosphere(t,dt){const E=environment,night=1-THREE.MathUtils.clamp((Math.sin((E.hour-6)/12*Math.PI)+.08)/.55,0,1),weatherDark=E.weather==='rain'?.48:E.weather==='fog'?.75:1;sun.intensity=(.18+(1-night)*2.15)*weatherDark;ambient.intensity=.55+(1-night)*1.2;sun.color.set(E.hour>16&&E.hour<20?0xffc68f:0xffefda);const daylight=THREE.MathUtils.clamp((E.hour-6)/12,0,1);sun.position.set(-22*Math.cos(daylight*Math.PI),15+Math.sin(daylight*Math.PI)*18,14);
const target=(E.weather==='rain'?wetBG:E.weather==='fog'?fogBG:E.weather==='snow'?snowBG:clearBG).clone().lerp(nightBG,night*.86);if(!scene.background)scene.background=target;scene.background.lerp(target,.05);scene.fog.color.copy(scene.background);scene.fog.density=THREE.MathUtils.lerp(scene.fog.density,E.weather==='fog'?.019:E.weather==='rain'?.009:.004,.04);
rain.visible=E.weather==='rain';snow.visible=E.weather==='snow';const arr=rain.geometry.attributes.position.array;if(rain.visible&&E.motion){for(let i=0;i<arr.length;i+=6){arr[i]+=.5*E.wind*dt;arr[i+1]-=11*dt;arr[i+2]-=.7*dt;if(arr[i+1]<.5){arr[i+1]=18;arr[i]=range(-16,16);arr[i+2]=range(-16,16);}arr[i+3]=arr[i]-.07;arr[i+4]=arr[i+1]+.40;arr[i+5]=arr[i+2]-.02;}rain.geometry.attributes.position.needsUpdate=true;}
if(snow.visible&&E.motion){const a=snow.geometry.attributes.position.array;for(let i=0;i<a.length;i+=3){a[i]+=Math.sin(t+a[i+2])*dt*.15+E.wind*.2*dt;a[i+1]-=dt*.65;if(a[i+1]<.5)a[i+1]=18;}snow.geometry.attributes.position.needsUpdate=true;}
for(const s of smoke){const a=(t*.09+s.phase)%1;s.mesh.position.copy(s.origin).add(new THREE.Vector3(a*.55*E.wind,a*2.8,Math.sin(a*4+s.phase)*.13));s.mesh.scale.setScalar(.55+a*2.2);s.mesh.material.opacity=(1-a)*.21;}
for(const c of clouds){c.g.position.x=c.x+Math.sin(t*.018+c.phase)*2.8;c.g.position.z=c.z+Math.sin(t*.01+c.phase)*.45;}
for(const w of waterMeshes){w.material.color.set(0x76b0ab).lerp(new THREE.Color(0xafcac3),.04+.05*Math.sin(t*1.2+w.position.x));}
for(const w of windows){w.material.emissive.set(0xe5a54c);w.material.emissiveIntensity=night*.8;}
sun.intensity*=1+Math.sin(t*.06)*.025;
}
