import './style.css';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createIcons, Castle, MapPin, SlidersHorizontal, Sun, Cloud, CloudRain, Snowflake, Sunrise, Moon, Wind, Mouse, Orbit, Scan, Maximize } from 'lucide';
import { createWorld } from './world.js';
import { createActors } from './actors.js';

const icons={Castle,MapPin,SlidersHorizontal,Sun,Cloud,CloudRain,Snowflake,Sunrise,Moon,Wind,Mouse,Orbit,Scan,Maximize};
createIcons({icons});
const canvas=document.querySelector('#world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const scene=new THREE.Scene();
const camera=new THREE.OrthographicCamera();camera.position.set(32,28,38);scene.userData.camera=camera;
const controls=new OrbitControls(camera,canvas);controls.target.set(0,2,0);controls.enableDamping=true;controls.dampingFactor=.055;controls.enablePan=false;controls.minZoom=.7;controls.maxZoom=2.6;controls.minPolarAngle=.3;controls.maxPolarAngle=Math.PI/2.35;controls.autoRotateSpeed=.32;controls.update();
function resize(){let aspect=innerWidth/innerHeight;let h=innerWidth<650?43/aspect:37;camera.left=-h*aspect/2;camera.right=h*aspect/2;camera.top=h/2;camera.bottom=-h/2;camera.near=.1;camera.far=200;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
resize();window.addEventListener('resize',resize);
const ambient=new THREE.HemisphereLight(0xf4edd9,0x777e5d,1.8);scene.add(ambient);
const sun=new THREE.DirectionalLight(0xffe7bb,3.2);sun.position.set(-15,30,15);sun.castShadow=true;sun.shadow.mapSize.set(innerWidth<650?1024:2048,innerWidth<650?1024:2048);sun.shadow.camera.left=-24;sun.shadow.camera.right=24;sun.shadow.camera.top=24;sun.shadow.camera.bottom=-24;sun.shadow.camera.near=.5;sun.shadow.camera.far=90;sun.shadow.normalBias=.035;sun.shadow.bias=-.0002;sun.shadow.radius=3;scene.add(sun);
const fill=new THREE.DirectionalLight(0xb9d6d1,.55);fill.position.set(18,12,-10);scene.add(fill);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(300,300),new THREE.ShadowMaterial({color:0x5d6451,opacity:.14}));floor.rotation.x=-Math.PI/2;floor.position.y=-.75;floor.receiveShadow=true;scene.add(floor);
// A broad feathered contact shadow gives the model a tangible exhibition-table setting.
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=256;const ctx=shadowCanvas.getContext('2d');let grad=ctx.createRadialGradient(128,128,30,128,128,128);grad.addColorStop(0,'rgba(68,78,49,.19)');grad.addColorStop(.5,'rgba(68,78,49,.12)');grad.addColorStop(1,'rgba(68,78,49,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,256,256);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(48,48),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(.7,-.74,.7);scene.add(shadow);
const world=createWorld(scene);const actors=createActors(THREE,scene);
// Weather particles stay contained over the little land rather than washing over the UI.
const particleCount=1100,positions=new Float32Array(particleCount*3);let weatherSeed=37;const random=()=>{weatherSeed=(weatherSeed*16807)%2147483647;return(weatherSeed-1)/2147483646;};for(let i=0;i<particleCount;i++){positions[i*3]=(random()-.5)*29;positions[i*3+1]=random()*17+1;positions[i*3+2]=(random()-.5)*29;}
const particleGeometry=new THREE.BufferGeometry();particleGeometry.setAttribute('position',new THREE.BufferAttribute(positions,3));
const snowCanvas=document.createElement('canvas');snowCanvas.width=snowCanvas.height=32;const sc=snowCanvas.getContext('2d');const sg=sc.createRadialGradient(16,16,1,16,16,15);sg.addColorStop(0,'rgba(255,255,255,1)');sg.addColorStop(.4,'rgba(255,255,255,.8)');sg.addColorStop(1,'rgba(255,255,255,0)');sc.fillStyle=sg;sc.fillRect(0,0,32,32);const snowTexture=new THREE.CanvasTexture(snowCanvas);
const particleMaterial=new THREE.PointsMaterial({color:0xecf3ed,size:.11,transparent:true,opacity:0,depthWrite:false,map:snowTexture});const particles=new THREE.Points(particleGeometry,particleMaterial);scene.add(particles);
const rainPositions=new Float32Array(450*6);const rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPositions,3));const rain=new THREE.LineSegments(rainGeo,new THREE.LineBasicMaterial({color:0xa0b0ac,transparent:true,opacity:0,depthWrite:false}));scene.add(rain);
const settings={weather:'sunny',hour:15,motion:true};let time=0,last=performance.now();
const weatherConfigs={sunny:{title:'Golden afternoon',detail:'Clear skies, a gentle breeze',icon:'sun',sun:2.7,ambient:1.8,bg:'#e9e9df'},cloudy:{title:'A softer sky',detail:'Cloud cover, a quiet valley',icon:'cloud',sun:1.1,ambient:1.9,bg:'#dfe4df'},rainy:{title:'Passing showers',detail:'A little rain for the harvest',icon:'cloud-rain',sun:.7,ambient:1.6,bg:'#d5dedb'},snowy:{title:'Winter whispers',detail:'Soft snow, warm hearths',icon:'snowflake',sun:1.6,ambient:1.9,bg:'#e5e9e6'}};
function setWeather(type){settings.weather=type;const w=weatherConfigs[type];document.querySelectorAll('.weather-button').forEach(b=>{b.classList.toggle('active',b.dataset.weather===type);b.setAttribute('aria-pressed',b.dataset.weather===type);});document.querySelector('#weather-title').textContent=w.title;document.querySelector('#weather-detail').textContent=w.detail;document.querySelector('#weather-symbol').innerHTML=`<i data-lucide="${w.icon}"></i>`;createIcons({icons});document.body.style.background=w.bg;document.body.style.transition='background 1.5s';document.querySelector('#world-status').textContent=type==='rainy'?'Even the smallest fields need rain.':type==='snowy'?'A little winter magic.':type==='cloudy'?'Clouds take the scenic route.':'Life moves at its own pace.';}
document.querySelectorAll('.weather-button').forEach(b=>b.addEventListener('click',()=>setWeather(b.dataset.weather)));
const slider=document.querySelector('#time-slider');slider.addEventListener('input',()=>{settings.hour=+slider.value;const h=Math.floor(settings.hour),m=Math.floor((settings.hour-h)*60);document.querySelector('#time-value').textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;slider.style.background=`linear-gradient(to right,#6e7d56 ${(settings.hour-6)/16*100}%,#dce0d3 ${(settings.hour-6)/16*100}%)`;});
document.querySelector('#motion-toggle').addEventListener('click',e=>{settings.motion=!settings.motion;e.currentTarget.classList.toggle('on',settings.motion);e.currentTarget.setAttribute('aria-pressed',settings.motion);});
document.querySelector('#rotate-toggle').addEventListener('click',e=>{controls.autoRotate=!controls.autoRotate;e.currentTarget.classList.toggle('active',controls.autoRotate);e.currentTarget.setAttribute('aria-pressed',controls.autoRotate);});
document.querySelector('#reset-view').addEventListener('click',()=>{camera.position.set(32,28,38);camera.zoom=1;controls.target.set(0,2,0);controls.autoRotate=false;document.querySelector('#rotate-toggle').classList.remove('active');camera.updateProjectionMatrix();controls.update();});
document.querySelector('#fullscreen').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch(e){console.warn('Fullscreen unavailable',e);}});
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;if(settings.motion)time+=dt;world.update(time);actors.update(time,settings.motion?dt:0);controls.update();const w=weatherConfigs[settings.weather],day=Math.max(.12,Math.sin((settings.hour-6)/16*Math.PI));const night=settings.hour>19;sun.intensity=THREE.MathUtils.lerp(sun.intensity,w.sun*day,.025);ambient.intensity=THREE.MathUtils.lerp(ambient.intensity,w.ambient*(.45+day*.55),.025);sun.color.lerp(new THREE.Color(settings.hour>18?0xffb780:settings.hour<9?0xffdab0:0xffe7bb),.015);sun.position.x=THREE.MathUtils.lerp(sun.position.x,-15+(settings.hour-15)*3,.012);fill.intensity=night?.75:.55;const opacity=settings.weather==='snowy'?.85:0;particleMaterial.opacity=THREE.MathUtils.lerp(particleMaterial.opacity,opacity,.05);rain.material.opacity=THREE.MathUtils.lerp(rain.material.opacity,settings.weather==='rainy'?.4:0,.05);for(const c of world.animations.clouds){c.scale.setScalar(settings.weather==='sunny'?1:1.45);}
 if(settings.motion&&(particleMaterial.opacity>.01||rain.material.opacity>.01)){for(let i=0;i<particleCount;i++){positions[i*3+1]-=dt*(settings.weather==='snowy'?.85:10);positions[i*3]+=Math.sin(time*.7+i)*dt*.12;if(positions[i*3+1]<.9){positions[i*3+1]=17;positions[i*3]=(random()-.5)*29;}if(i<450){let k=i*6;rainPositions[k]=positions[i*3];rainPositions[k+1]=positions[i*3+1];rainPositions[k+2]=positions[i*3+2];rainPositions[k+3]=positions[i*3]+.07;rainPositions[k+4]=positions[i*3+1]+.47;rainPositions[k+5]=positions[i*3+2];}}particleGeometry.attributes.position.needsUpdate=true;rainGeo.attributes.position.needsUpdate=true;}
 renderer.render(scene,camera);}
requestAnimationFrame(animate);requestAnimationFrame(()=>document.querySelector('#loading').classList.add('hidden'));
// Exposed for diagnostics without affecting the uncluttered experience.
window.__littleWorld={scene,camera,renderer,settings,setWeather};
