import {test} from 'node:test';
import assert from 'node:assert/strict';
import {allocateId,formatId,formatTitle,canonicalHarness} from './naming.mjs';
import {promoteCase} from './promote-case.mjs';
import {readCases,caseDir} from './lib.mjs';
import {resolveWithin} from './lib.mjs';
import {assertReady,reviewCurrent} from './verification.mjs';
test('别名与稳定组合不会覆盖既有运行',async()=>{const c=(await readCases())[0];const next=await allocateId({...c,harness:c.harness==='Pi'?'PI':c.harness});assert.notEqual(next.id,c.id);assert.ok(next.serial>c.serial);assert.equal(formatId({...c,harness:canonicalHarness(c.harness)},c.serial),c.id);assert.equal(formatTitle(c),c.title);});
test('失败产物和未人工检查的候选不能进入正式案例',async()=>{for(const status of ['pending','built','runtime-failed','build-failed'])await assert.rejects(promoteCase({id:'rejected',status,cover:'x',demoFingerprint:'x',verification:{manualReview:{summary:'x'}}}),/必须通过/);await assert.rejects(promoteCase({id:'rejected',status:'verified',cover:'x',demoFingerprint:'x',verification:{}}),/人工复核/);});
test('案例入口拒绝路径越界',async()=>{await assert.rejects(caseDir('../cases'),/ID|非法/);});
test('重新构建后旧验收记录失效',()=>{const c={id:'fixture',status:'verified',cover:'cover.webp',sourceFingerprint:'source-a',demoFingerprint:'demo-a'};c.verification={ok:true,...c,manualReview:{sourceFingerprint:c.sourceFingerprint,demoFingerprint:c.demoFingerprint,summary:'实际画面'}};assert.equal(reviewCurrent(c),true);assertReady(c);assert.throws(()=>assertReady({...c,demoFingerprint:'demo-b'}),/当前产物/);assert.throws(()=>assertReady({...c,sourceFingerprint:'source-b'}),/当前产物/);});
test('路径边界不接受同名前缀的兄弟目录',()=>{assert.throws(()=>resolveWithin('E:/tmp/gallery-build/case-a','../case-a-other/index.html'),/越界/);});
